# Site settings
title: Tianran Chen
email: chentia1@msu.edu
description: "Tianran Chen's homepage"
baseurl: ""
url: "http://chentianran.github.io"
github_username:  chentianran

# Build settings
markdown: kramdown
permalink: pretty
