# Site settings
title: Tianran Chen
email: ti@nranchen.org
description: "Tianran Chen's homepage"
baseurl: ""
url: "http://chentianran.github.io"
github_username:  chentianran

# Build settings
markdown: kramdown
permalink: pretty
exclude: [ vendor ]
